//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.UserAccountAdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAccountAdminService.IUserAccountAdminService")]
    public interface IUserAccountAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountAdminService/InsertPerson", ReplyAction="http://tempuri.org/IUserAccountAdminService/InsertPersonResponse")]
        void InsertPerson(AcademicsServicesDIPP.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountAdminService/GetPerson", ReplyAction="http://tempuri.org/IUserAccountAdminService/GetPersonResponse")]
        long GetPerson(long ci, string nombre, string aP, string aM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountAdminService/InsertUserAccount", ReplyAction="http://tempuri.org/IUserAccountAdminService/InsertUserAccountResponse")]
        void InsertUserAccount(AcademicsServicesDIPP.UserAccount useraccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountAdminService/InsertUserRole", ReplyAction="http://tempuri.org/IUserAccountAdminService/InsertUserRoleResponse")]
        void InsertUserRole(AcademicsServicesDIPP.UserRole userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountAdminService/UpdateUserAccount", ReplyAction="http://tempuri.org/IUserAccountAdminService/UpdateUserAccountResponse")]
        void UpdateUserAccount(AcademicsServicesDIPP.UserAccount entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountAdminService/GetUserID", ReplyAction="http://tempuri.org/IUserAccountAdminService/GetUserIDResponse")]
        long GetUserID(string account, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAccountAdminServiceChannel : QualificationsWebSystem.UserAccountAdminService.IUserAccountAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAccountAdminServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.UserAccountAdminService.IUserAccountAdminService>, QualificationsWebSystem.UserAccountAdminService.IUserAccountAdminService {
        
        public UserAccountAdminServiceClient() {
        }
        
        public UserAccountAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAccountAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccountAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccountAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertPerson(AcademicsServicesDIPP.Person person) {
            base.Channel.InsertPerson(person);
        }
        
        public long GetPerson(long ci, string nombre, string aP, string aM) {
            return base.Channel.GetPerson(ci, nombre, aP, aM);
        }
        
        public void InsertUserAccount(AcademicsServicesDIPP.UserAccount useraccount) {
            base.Channel.InsertUserAccount(useraccount);
        }
        
        public void InsertUserRole(AcademicsServicesDIPP.UserRole userRole) {
            base.Channel.InsertUserRole(userRole);
        }
        
        public void UpdateUserAccount(AcademicsServicesDIPP.UserAccount entity) {
            base.Channel.UpdateUserAccount(entity);
        }
        
        public long GetUserID(string account, string pass) {
            return base.Channel.GetUserID(account, pass);
        }
    }
}
