//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.ProgramService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProgramService.IAcademicService")]
    public interface IAcademicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademicService/InsertProgram", ReplyAction="http://tempuri.org/IAcademicService/InsertProgramResponse")]
        void InsertProgram(AcademicsServicesDIPP.GraduateProgram entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademicService/UpdateProgram", ReplyAction="http://tempuri.org/IAcademicService/UpdateProgramResponse")]
        void UpdateProgram(AcademicsServicesDIPP.GraduateProgram entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademicService/GetAll", ReplyAction="http://tempuri.org/IAcademicService/GetAllResponse")]
        AcademicsServicesDIPP.Program[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademicService/GetProgramID", ReplyAction="http://tempuri.org/IAcademicService/GetProgramIDResponse")]
        long GetProgramID(string nameProgram);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAcademicServiceChannel : QualificationsWebSystem.ProgramService.IAcademicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcademicServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.ProgramService.IAcademicService>, QualificationsWebSystem.ProgramService.IAcademicService {
        
        public AcademicServiceClient() {
        }
        
        public AcademicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcademicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcademicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcademicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertProgram(AcademicsServicesDIPP.GraduateProgram entity) {
            base.Channel.InsertProgram(entity);
        }
        
        public void UpdateProgram(AcademicsServicesDIPP.GraduateProgram entity) {
            base.Channel.UpdateProgram(entity);
        }
        
        public AcademicsServicesDIPP.Program[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public long GetProgramID(string nameProgram) {
            return base.Channel.GetProgramID(nameProgram);
        }
    }
}
