//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.StudentModuleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentModuleService.IStudentModuleAdminService")]
    public interface IStudentModuleAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentModuleAdminService/InsertStudentModule", ReplyAction="http://tempuri.org/IStudentModuleAdminService/InsertStudentModuleResponse")]
        void InsertStudentModule(AcademicsServicesDIPP.StudentModule entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentModuleAdminService/GetStudentModuleId", ReplyAction="http://tempuri.org/IStudentModuleAdminService/GetStudentModuleIdResponse")]
        long GetStudentModuleId(long teaching, long stydentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentModuleAdminServiceChannel : QualificationsWebSystem.StudentModuleService.IStudentModuleAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentModuleAdminServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.StudentModuleService.IStudentModuleAdminService>, QualificationsWebSystem.StudentModuleService.IStudentModuleAdminService {
        
        public StudentModuleAdminServiceClient() {
        }
        
        public StudentModuleAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentModuleAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentModuleAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentModuleAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertStudentModule(AcademicsServicesDIPP.StudentModule entity) {
            base.Channel.InsertStudentModule(entity);
        }
        
        public long GetStudentModuleId(long teaching, long stydentId) {
            return base.Channel.GetStudentModuleId(teaching, stydentId);
        }
    }
}
