//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.ModuleAsignationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModuleAsignationService.IModuleAsigAdminService")]
    public interface IModuleAsigAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAsigAdminService/GetPensumID", ReplyAction="http://tempuri.org/IModuleAsigAdminService/GetPensumIDResponse")]
        int GetPensumID(int ProgramID, int ModuleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAsigAdminService/InsertAsignation", ReplyAction="http://tempuri.org/IModuleAsigAdminService/InsertAsignationResponse")]
        void InsertAsignation(AcademicsServicesDIPP.Pensum entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAsigAdminService/UpdateAsignation", ReplyAction="http://tempuri.org/IModuleAsigAdminService/UpdateAsignationResponse")]
        void UpdateAsignation(int PensumID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuleAsigAdminServiceChannel : QualificationsWebSystem.ModuleAsignationService.IModuleAsigAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuleAsigAdminServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.ModuleAsignationService.IModuleAsigAdminService>, QualificationsWebSystem.ModuleAsignationService.IModuleAsigAdminService {
        
        public ModuleAsigAdminServiceClient() {
        }
        
        public ModuleAsigAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuleAsigAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAsigAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAsigAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetPensumID(int ProgramID, int ModuleID) {
            return base.Channel.GetPensumID(ProgramID, ModuleID);
        }
        
        public void InsertAsignation(AcademicsServicesDIPP.Pensum entity) {
            base.Channel.InsertAsignation(entity);
        }
        
        public void UpdateAsignation(int PensumID) {
            base.Channel.UpdateAsignation(PensumID);
        }
    }
}
