//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.QualificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QualificationService.IQualificationAdminService")]
    public interface IQualificationAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQualificationAdminService/InsertQualification", ReplyAction="http://tempuri.org/IQualificationAdminService/InsertQualificationResponse")]
        void InsertQualification(AcademicsServicesDIPP.Qualifications entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQualificationAdminService/GetQualificationId", ReplyAction="http://tempuri.org/IQualificationAdminService/GetQualificationIdResponse")]
        float GetQualificationId(long evalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQualificationAdminService/InsertQualificationTotals", ReplyAction="http://tempuri.org/IQualificationAdminService/InsertQualificationTotalsResponse")]
        void InsertQualificationTotals(AcademicsServicesDIPP.Totals entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQualificationAdminServiceChannel : QualificationsWebSystem.QualificationService.IQualificationAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QualificationAdminServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.QualificationService.IQualificationAdminService>, QualificationsWebSystem.QualificationService.IQualificationAdminService {
        
        public QualificationAdminServiceClient() {
        }
        
        public QualificationAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QualificationAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualificationAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualificationAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertQualification(AcademicsServicesDIPP.Qualifications entity) {
            base.Channel.InsertQualification(entity);
        }
        
        public float GetQualificationId(long evalCode) {
            return base.Channel.GetQualificationId(evalCode);
        }
        
        public void InsertQualificationTotals(AcademicsServicesDIPP.Totals entity) {
            base.Channel.InsertQualificationTotals(entity);
        }
    }
}
