//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.InscriptionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InscriptionService.IInscriptionAdminService")]
    public interface IInscriptionAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionAdminService/InsertProgram", ReplyAction="http://tempuri.org/IInscriptionAdminService/InsertProgramResponse")]
        void InsertProgram(AcademicsServicesDIPP.GraduateProgram entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionAdminService/UpdateProgram", ReplyAction="http://tempuri.org/IInscriptionAdminService/UpdateProgramResponse")]
        void UpdateProgram(AcademicsServicesDIPP.GraduateProgram entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInscriptionAdminServiceChannel : QualificationsWebSystem.InscriptionService.IInscriptionAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InscriptionAdminServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.InscriptionService.IInscriptionAdminService>, QualificationsWebSystem.InscriptionService.IInscriptionAdminService {
        
        public InscriptionAdminServiceClient() {
        }
        
        public InscriptionAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InscriptionAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscriptionAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscriptionAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertProgram(AcademicsServicesDIPP.GraduateProgram entity) {
            base.Channel.InsertProgram(entity);
        }
        
        public void UpdateProgram(AcademicsServicesDIPP.GraduateProgram entity) {
            base.Channel.UpdateProgram(entity);
        }
    }
}
