//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.PolicyPasswordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PolicyPasswordService.IPolicyPasswordAdminService")]
    public interface IPolicyPasswordAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyPasswordAdminService/InsertPolicyPassw0rd", ReplyAction="http://tempuri.org/IPolicyPasswordAdminService/InsertPolicyPassw0rdResponse")]
        void InsertPolicyPassw0rd(AcademicsServicesDIPP.PasswordPolicy enitity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyPasswordAdminService/GetPolicyPassword", ReplyAction="http://tempuri.org/IPolicyPasswordAdminService/GetPolicyPasswordResponse")]
        string GetPolicyPassword();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolicyPasswordAdminServiceChannel : QualificationsWebSystem.PolicyPasswordService.IPolicyPasswordAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolicyPasswordAdminServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.PolicyPasswordService.IPolicyPasswordAdminService>, QualificationsWebSystem.PolicyPasswordService.IPolicyPasswordAdminService {
        
        public PolicyPasswordAdminServiceClient() {
        }
        
        public PolicyPasswordAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolicyPasswordAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyPasswordAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyPasswordAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertPolicyPassw0rd(AcademicsServicesDIPP.PasswordPolicy enitity) {
            base.Channel.InsertPolicyPassw0rd(enitity);
        }
        
        public string GetPolicyPassword() {
            return base.Channel.GetPolicyPassword();
        }
    }
}
