//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualificationsWebSystem.EvaluationPlanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvaluationPlanService.IEvaluationPlanAdminService")]
    public interface IEvaluationPlanAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationPlanAdminService/InsertEvaluationPlan", ReplyAction="http://tempuri.org/IEvaluationPlanAdminService/InsertEvaluationPlanResponse")]
        void InsertEvaluationPlan(AcademicsServicesDIPP.EvaluationPlan entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationPlanAdminService/InsertEvaluationFinal", ReplyAction="http://tempuri.org/IEvaluationPlanAdminService/InsertEvaluationFinalResponse")]
        void InsertEvaluationFinal(AcademicsServicesDIPP.EndEvaluation entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluationPlanAdminService/GetEvaluationPlanID", ReplyAction="http://tempuri.org/IEvaluationPlanAdminService/GetEvaluationPlanIDResponse")]
        long GetEvaluationPlanID(long globalPlanID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvaluationPlanAdminServiceChannel : QualificationsWebSystem.EvaluationPlanService.IEvaluationPlanAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvaluationPlanAdminServiceClient : System.ServiceModel.ClientBase<QualificationsWebSystem.EvaluationPlanService.IEvaluationPlanAdminService>, QualificationsWebSystem.EvaluationPlanService.IEvaluationPlanAdminService {
        
        public EvaluationPlanAdminServiceClient() {
        }
        
        public EvaluationPlanAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvaluationPlanAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvaluationPlanAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvaluationPlanAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertEvaluationPlan(AcademicsServicesDIPP.EvaluationPlan entity) {
            base.Channel.InsertEvaluationPlan(entity);
        }
        
        public void InsertEvaluationFinal(AcademicsServicesDIPP.EndEvaluation entity) {
            base.Channel.InsertEvaluationFinal(entity);
        }
        
        public long GetEvaluationPlanID(long globalPlanID) {
            return base.Channel.GetEvaluationPlanID(globalPlanID);
        }
    }
}
